server:
  port: 8089

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

# 整合mybatis
mybatis:
  type-aliases-package: com.pat.jp.system.modules.system.domain # 配置类路径别名
  mapper-locations: classpath:mybatis/mapper/*.xml

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLJTU7BWPPU2xOA4P3Uqszg7+3LbtvYoj2TT70uacyM217CcMIHVCRHIXxLxxC6NchE0e4E+qyU6+gOAV4wME+gVyHTPKj499V264nQySOwDGhBe7Ftu+X5w0zi7cT5efVCv8WtYryzGnbdpnDUP6NsDfX5/BbNfvmbUvTBKuGPSD8fYljVHfNy7C6l+MjIYXmrCc4TdIFtu5TbZi2JkElBnmHDO/+lF14Uh7jxcYv2XkLovvdCLaqinAczX3xFq6xR4t9xOTrFKMIfUydMhoe+wC07Z82NP7VWrSHMg3GdRYUlbDg0xNNInnbbQ57BvZLPYglMU0ErM5x7MV5oIt5AgMBAAECggEADCz2u8re6JY/b42WY0R5LmU/IGOFUG+/dcO7ej+GXePnM/Cp19qp8YicHpCMSRZbjofxTH8lGfsaE6hH66zh6DUorpNWF6yYvjSkg4XqswOh9dy9KuyD/77Bc81z86Vb99Do6RuIcHUAAz9gh+xa1XMyZaZpKY5awrzaRpOJFEqKUQRSpN6TWSUHy0xXB9dx4tUtFikyuN66dCQAp7+10tY1q8Ij0J5YNGGEYiNwbQfXWCay47u+nVXYARRdHNBTCGYgl/GVdSdTNQlrnSEHZybGkNuBr44SERIRPMSBTuJ+OiaeL9OkVQGUr8ERZlMRSNLqaSy9Q+Q96gj23YDTgQKBgQDmfr9U8SmgiJ2OISfxdFBU+lkAGYRTNZMWHHUhZSZcx4wDtt5oaETkp6jAD6dgYR//01BKCNlG4BDGv0eVzLjVsy6bWZjHVhV1SaAYwtWNlXfGWehMPFNNlXcTW22L2Jz3u8SxQ499rc6EzkGlw0UZQNsn5WJAW/nxWhPpw6xGbQKBgQDhn7jAnu1NpJGokulGZWa3SsGxEd1AHLBm4yDSUHRRsKMYW2djbotgp1wn2E0nu2p1kiD3A7hoa9BihvL+fCBVjnIHurXuN+DqM9/EXwMYxyec69SraXlPSQEytppmmJxY9fV5MshEPnyD0uu5knKjb0JcVT2vSjrT0g37F/6hvQKBgQDjinJlb2HRuawYGEEvSszW5wGfaJFJ95SJenRjEFDLvK5LKGbtGSoRtDWRzKJGMft9+GTFgXDFWAMXwNLxXdWGGUpEUDHTbvbl/1XNu+FH0SsZo74ALHlsGMYhVNuS97cVlMa62+A2iLNcRaVm95sqL+1puDfDI0ld6rfHyMQ0DQKBgARQTnL4VucmH1bOwEEFTUpx1nQxOD6yjbjZ3NXIjgDF1Mhxbu+avHVznbJxU0BQN//ZdGHko1Dzxr8rf1fYPbIFEC8PpczRKq6voTaa7m8514sLgzxnvtcCOVCj5x3RCyQ0R6Yyj1umqjDHBpS8tQ5k4SrswkoorClCmdvUIJ0tAoGAFJWKe9Rbm8D/78gyESse9VfWmz/UqkitbxiFUxiAUMudfVTkcPB9wICzxgtNT8iC+0hzSLvxd32fmGLlWZ9rbt7+TTRNC+nHpVxkenLSYBuTw/Q598XK6ui1WxcZXwSqaOXACe/z93n+0eGLXySejZK2Fw0Hdw761MDvKuHKRqU=
