server:
  port: 8089

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

# 整合mybatis
mybatis:
  type-aliases-package: com.pat.jp.hellotest.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
